### ISSUE TITLE
Ninirim Collection

### ISSUE THREAD

**Issue by WinterdrakeX** [JaxomofRuatha/ls2-extra-mods-unofficial#10]
**[SunJeong] Ninirim Collection 6.0**

*(Site Link)*
** https://sunkeumjeong.wixsite.com/mysite/post/sunjeong-ninirim-collection-6-0 **

*(File link)*
**http://www.mediafire.com/file/h40zast0ozolmwx/%255BSunJeong%255D_Ninirim_Collection_6.0_FOMOD.7z/file**

**Summary:**

Adds a museum containing huge amounts of custom female armor for CBBE.

**LS2 Compatibility Status:**

Good (no issues after patching)

**Recommendation:**

*WinterdrakeX (Highly Recommend)

**Official Patches:**

None

**Custom Patches:**

"Requires patching for Occlusion.esp"

**Load/Install Order Notes:**

* WinterdrakeX(LS2 version 2.2.1)
Install and move this mod upwards before the separator named 'Items - Female Armors'
It should only overwrite 'unofficial performance optimized textures AKA (UPOT). Let others overwrite it.

Put [Sunjeong] Ninirim Collection.esp a few mods before ELE_SSE.esp (apparently if you stick some mod right before ELE_SSE.esp it sometimes still overwrite ELE_SSE.esp).

**Extra Notes:**

Credits for the outfits go to Ninirim for the countless years of work he's done. Included more specific credits in an in-game poster inside the museum.

(Note to JaxomofRuatha: only needs patching in Worldspace/0000003C/Block -1,-1/Sub block -1,-2/00009b93 ; add 'Editor ID' and 'XCMO - music type' from [Sunjeong] Ninirim Collection.esp to Occlusion.esp. Everything else seems ok, tried and tested.)

**Comment by JaxomofRuatha** [comment]
Added as a new mod! Will update with custom patch when able.
