### ISSUE TITLE
Jesus In Skyrim

### ISSUE THREAD

**Issue by WinterdrakeX** [JaxomofRuatha/ls2-extra-mods-unofficial#11]
**Jesus In Skyrim**

**https://www.nexusmods.com/skyrimspecialedition/mods/20956?tab=files**

**Summary:**

Jesus is a fully voiced follower with unique magic, thousands of comments, responses, taunts, jokes, religious memes, song parodies etc.
Accept Jesus as your personal savior!

**LS2 Compatibility Status:**

Excellent (no issues, no patching required)

**Recommendation:**

WinterdrakeX (Highly Recommend)

**Official Patches:**

None

**Custom Patches:**

None

**Load/Install Order Notes:**

* WinterdrakeX (LS2 version 2.2.1)
* Move akornojesus.esp before ELE_SSE.esp

**Extra Notes:**

He is not essential (for the memes). Avoid Jesus' death by fire, shock or anything that would mess up his corpse. It will sometimes screw with his scripted resurrection. Other than that, great follower, I rate him higher than Recorder.

**Comment by KNGLogan** [comment]
alduin save lol?

**Comment by JaxomofRuatha** [comment]
Added new mod! And none of that tyranny here @KNGLogan 😛
