### ISSUE TITLE
Aetherium Armor and Weapons Compilation by lautasantenni

### ISSUE THREAD

**Issue by WinterdrakeX** [JaxomofRuatha/ls2-extra-mods-unofficial#12]
## Aetherium Armor and Weapons Compilation by Lautasantenni

**Link:** https://www.nexusmods.com/skyrimspecialedition/mods/2687

**Summary:** Adds 2 Power Armor Sets and many weapons after unlocking the Aetherium Forge. Can be displayed at the museum using
the LOTD patch.

**LS2 Compatibility Status:** Good (no known stability issues with or without the LOTD patch)

**Recommendations:** 
* WinterdrakeX (Highly Recommend)

**Official Patches:**
* https://www.nexusmods.com/skyrimspecialedition/mods/30980 (Note: contains 2 ESPs)
* https://www.nexusmods.com/skyrimspecialedition/mods/31416?tab=files (patch for respawnable aetherium ore, also grab the shield mesh fix if you need it)

* https://www.nexusmods.com/skyrimspecialedition/mods/24094?tab=files (shiny-bright better armor textures)

**Custom Patches:**
_None_

**Load/Install Order Notes:**
* WinterdrakeX (LS2 version 2.2.1)
  * AetheriumSwordsnArmor.esp must be loaded before ELE_SSE.esp
  * DBM_AetheriumWeapons_Patch.esp and DBM_ISC_Patch loaded before Bashed Patch, 0.esp (NOTE: I reinstalled the Legacy of the Dragonborn Official Patches with a different name and no other patches enabled to get this)
  * Aetherium Ore Respawns.esp immediately after AetheriumSwordsnArmor.esp ; Aetherium Shield Menu Mesh Fix and Texture Enhancements anywhere after AetheriumArmornWeapons mod.
**Extra Notes:**
* Weapons and armor pieces are not currently marked by the Curator's Companion. Will still be displayed if auto-sorted.
* Finish the vanilla quests "Lost to the Ages" and "Unfathomable Depths" in order to unlock the Recipes. Can only be crafted using the Aetherium Forge.

**Comment by JaxomofRuatha** [comment]
Made changes requested!
