### ISSUE TITLE
SSE Organic Factions / SSE Organic Factions Extension Version Update

### ISSUE THREAD

**Issue by ErikIEC** [JaxomofRuatha/ls2-extra-mods-unofficial#13]
**SSE Organic Factions / SSE Organic Factions Extension:**

**SSE Organic Factions Link:** https://www.nexusmods.com/skyrimspecialedition/mods/10289
**SSE Organic Factions Extension Link:** https://www.nexusmods.com/skyrimspecialedition/mods/25471

**Summary:** Both mods are already included in LS2.  This is an update to the latest versions on Nexus.
SSE Organic Factions are Factions which grow and change independent of the player. Factions Extension adds many Organic Factions to Skyrim.  It also includes several unique enemies and weapons / armor / items.

**LS2 Compatibility Status:** Good (Requires a patch, no instability issues for me).

**Recommendation:**

* Highly Recommended

**Official Patches:** _None_

Add links to downloads and instructions for any official patches used to get this mod compatible with LS

**Custom Patches:** https://drive.google.com/file/d/1flYxa19TAGgrK7Crj1oBAhbq0xztcNB4/view?usp=sharing

Forwards some entries for new items, matching what ForgottenGlory did with the previous stuff in other patches.  Left records modified by existing patches alone.

**Load/Install Order Notes:**

* Living Skyrim 2.4.0
* Download the 1.3 version of SSE Organic Factions.  Install and Merge with existing.
* Download the 1.041 version of SSE Organic Factions Extension.  Install and Merge  with existing.
* Put **OrganicFactionsExtension.esp** immediately after **Pre-Final Steps Merge.esp**
* Put **OrganicFactionsExtendedPatch.esp** immediately before **enemies_releveled.esp**

**Extra Notes:**

**OrganicFactionsExtendedPatch.esp** is ESL flagged so won't count against the load order.  I did not ESLify **LS2 Patches Merged.esp** or **enemies_releveled.esp** - you may be able to but I haven't tested that way.

**Comment by JaxomofRuatha** [comment]
Added update information to main README, I edited the plugin because there were some records that seemed to be pulling from Skyrim.esm but looks good after actually replacing the merged file!
