### ISSUE TITLE
(Realistic RS Children Overhauls)

### ISSUE THREAD

**Issue by KNGLogan** [JaxomofRuatha/ls2-extra-mods-unofficial#14]
the title

https://www.nexusmods.com/skyrimspecialedition/mods/39359?tab=files

**Summary:**

makes children look like childs and not adults from normal RS

**LS2 Compatibility Status:**

pretty compatible no know issues yet 
**Recommendation:**

 must add

**Official Patches:**

has helgan, lotd, ai overhaul, patches

**Custom Patches:**
no custom  
**Load/Install Order Notes:**

* running on 2.4
*you need rs children overhaul, than realistic overall, and patches under that 
**Extra Notes:**

pretty dope

**Comment by KNGLogan** [comment]
after occlusion esp

**Comment by JaxomofRuatha** [comment]
Added this with most recent update!
