### ISSUE TITLE
Valley of Outcasts & The Last Refuge

### ISSUE THREAD

**Issue by chosti-factor** [JaxomofRuatha/ls2-extra-mods-unofficial#15]
**Name of the mod (please use whatever the Nexus title is):**

Valley of Outcasts & The Last Refuge

**Download link for the mod:**

Valley of Outcasts (Part 1): https://www.nexusmods.com/skyrimspecialedition/mods/18175
The Last Refuge (Part 2): https://www.nexusmods.com/skyrimspecialedition/mods/27331

**Summary:**

From the Valley of Outcasts mod page: A freeform adventure centered around a large citadel in the Jerall Mountains. Over 1000 lines of voiced Dialogue and 12 quests oriented for all playstyles and made to integrate well with the base game.

From the Last Refuge mod page: The sequel to Valley of Outcasts, a year in the making. Go on an epic adventure to stop a powerful Lich from obtaining an Elder Scroll. Over 1200 lines of high-quality voice over, 9 major quests, and hours of new content.

**LS2 Compatibility Status:**

I played about 3 hours of Part 1 without any major issues. Consoled-started Part 2 and played about 1 hour without any major issues. SSEEdit shows some conflicts, but most of those are intended. Part 2 needs to be installed alongside Part 1, even if you only intend to play Part 1, as the bugfixes have been incorporated into Part 2. I'm very new to SSEEdit so I might have missed something, but mod was stable under LS 2.4.0.

**Recommendation:**

* Current level of recommendation: Ok
* Quick review: This mod adds content and a new area to build structures (similar to Blackthorn). As you build structures, quests become available. Quests and voice acting are of varying quality. Part 1 has some references to other games that may break the immersion for some (I found them funny because I'm a child). You have to talk to NPCs to get the quests. Quest markers can be a little iffy. 

**Official Patches:**

https://www.nexusmods.com/skyrimspecialedition/mods/18175?tab=files
Blackface Fixer 2 (essential)
Immersive Start (recommended)

**Custom Patches:**

None seem to be needed

**Load/Install Order Notes:**

* Include the version of LS you are currently running as the base
Living Skyrim 2.4.0

* Any information on how the files and  plugins added by this mod and the associated patches are added to LS. Include an unmodified LS mod/plugin as the guideline for before/after.

Load after More Gifts for Children.esl on the right pane. In this order:
JerralMountainsCitadel.esm
JerralMountainsCitadelPart1.esm
JerralMountainsCitadelPart2.esm

Blackface Fixer 2 patch can be loaded anywhere, I have it at the bottom of the left pane.
Immersive Start patch needs to be before LS2 Patches Merged on right pane.

**Extra Notes:**

Overall I think it's worth it to install, but it'll cost you 3 non-ESL slots (4 if you add the Immersive Start patch).

**Comment by JaxomofRuatha** [comment]
Added this with most recent update!
