### ISSUE TITLE
Pit Fighters Faction

### ISSUE THREAD

**Issue by chosti-factor** [JaxomofRuatha/ls2-extra-mods-unofficial#16]
**Name of the mod (please use whatever the Nexus title is):**

Faction - Pit Fighter

**Download link for the mod:**

https://www.nexusmods.com/skyrimspecialedition/mods/22513

**Summary:**

Pit Fighter contains an all new faction to join, complete with NPCs, progression through the ranks, unique rewards and side quests.

**LS2 Compatibility Status:**

Works well under 2.4.0

**Recommendation:**

* Current level of recommendation, high to low: Okay
* (Optional) add an actual review of the mod itself: Fun mod, battles with a wide range of character levels, good voice acting overall, and variety of setting for battles makes it worth the install.

**Official Patches:**

None needed for LS.

**Custom Patches:**

I created a custom patch to forward USSEP records that were being overwritten with Skyrim master records. Probably not necessary but better safe than sorry. ESP flagged as ESL.

[Pit Fighter Patch.zip](https://github.com/JaxomofRuatha/ls2-extra-mods-unofficial/files/5337768/Pit.Fighter.Patch.zip)

**Load/Install Order Notes:**

* Living Skyrim 2.4.0
* Load quest_pitfighter.esp, then quest_pitfighter_dlc01.esp; both before Clockwork.esp and Keld-Nar plugins.

**Extra Notes:**

Definitely don't forget to add the "Faction - Pit Figher Travels Add-on" optional file.

**Comment by chosti-factor** [comment]
Added custom patch.

**Comment by JaxomofRuatha** [comment]
Added this with most recent update!
