### ISSUE TITLE
The Shadow of Meresis

### ISSUE THREAD

**Issue by chosti-factor** [JaxomofRuatha/ls2-extra-mods-unofficial#17]
**Name of the mod (please use whatever the Nexus title is):**

The Shadow of Meresis

**Download link for the mod:**

https://www.nexusmods.com/skyrimspecialedition/mods/38167

**Summary:**

From the mod page: The Shadow of Meresis adds "an extensive quest, leading you to various places all over Skyrim. In addition to new locations and dungeons you'll meet new NPCs with more than 200 fully voiced lines of dialogue spoken by three actors. The playtime is about two to three hours."

**LS2 Compatibility Status:**

No issues under LS 2.4.0

**Recommendation:**

* Current level of recommendation, high to low: Highly recommended
* (Optional) add an actual review of the mod itself: Short but fun. Good voice acting and original quests made an enjoyable addition to my playthrough.

**Official Patches:**

None

**Custom Patches:**

Has minor conflicts with the Brotherhood of Old and Palaces and Castles Enhanced. The custom patch removes objects placed by Shadow of Meresis that block the entrance to the Fringe Sanctum (Brotherhood of Old). The patch also resolves an NPC placement conflict with PCE.

[LS2 Meresi Patch.zip](https://github.com/JaxomofRuatha/ls2-extra-mods-unofficial/files/5337800/LS2.Meresi.Patch.zip)
 
**Load/Install Order Notes:**

* Include the version of LS you are currently running as the base: LS 2.4.0
* Load Shadow of Meresis.esp before Brotherhood of Old and the patch LS2 Meresis Patch.esp before LS2 Patches Merged.

**Extra Notes:**

Unless you look for it, the quest won't start. There is a corpse in a mini-island across the Solitude sawmill. It's hard to find because of Living Skyrim's tall grasses, but it's there. Loot the corpse and wear the amulet to start the quest. From the mod page: The quest starts at the Solitude Sawmill (south of Katla's Farm) where you will find a corpse on a little sandbank in the middle of the river.

**Comment by JaxomofRuatha** [comment]
Added this with most recent update!
