### ISSUE TITLE
Relaxed Sneak Animations

### ISSUE THREAD

**Issue by chosti-factor** [JaxomofRuatha/ls2-extra-mods-unofficial#18]
**Name of the mod (please use whatever the Nexus title is):**

Relaxed Sneak Animations

**Download link for the mod:**

https://www.nexusmods.com/skyrimspecialedition/mods/37260?tab=posts

**Summary:**

From the mod page: Sneaking animations with a raised center of gravity, straighter posture with arms reeled in and no bent wrists.

**LS2 Compatibility Status:**

No issues in 2.4.0 after re-running FNIS.

**Recommendation:**

* Current level of recommendation, high to low: Highly Recommended
* (Optional) add an actual review of the mod itself: Sneak animations are much more natural. Followers look like they are sneaking, not squatting for other purposes...

**Official Patches:**

None

**Custom Patches:**

None needed

**Load/Install Order Notes:**

* Include the version of LS you are currently running as the base: 2.4.0
* Put Relaxed Sneak Animations after Pretty Combat Animations in the left pane.

**Extra Notes:**

Don't forget to re-run FNIS.

**Comment by JaxomofRuatha** [comment]
Added in most recent update!
