### ISSUE TITLE
Shadows of the Past

### ISSUE THREAD

**Issue by chosti-factor** [JaxomofRuatha/ls2-extra-mods-unofficial#19]
**Name of the mod (please use whatever the Nexus title is):**

Shadows of the Past SSE

**Download link for the mod:**

https://www.nexusmods.com/skyrimspecialedition/mods/4564

**Summary:**

From the mod page: A Tribute to TESIV Oblivion. Adds a fully voiced questline with 6 quests and and various new dungeons to the game. Queststart: go in a city or village and let the courier approach you.

**LS2 Compatibility Status:**

No problems under 2.4.0

**Recommendation:**

* Current level of recommendation, high to low: Highly Recommended.
* (Optional) add an actual review of the mod itself: On the short side, but fun. Voice acting is hit or miss. Environments added and quests are good quality.

**Official Patches:**

None

**Custom Patches:**

[LS2 - Shadows of the Past - Patch.zip](https://github.com/JaxomofRuatha/ls2-extra-mods-unofficial/files/5356014/LS2.-.Shadows.of.the.Past.-.Patch.zip)

The custom patch moves an entrance in one of the quests to get around the changes from JKs Skyrim. It also forwards navmesh records from Update.esm that seem to have been incorrectly missed. 

**Load/Install Order Notes:**

* Include the version of LS you are currently running as the base: 2.4.0
* Load AKShadowsOfThePast.esm before JKs Skyrim.esp on right pane (I have it high on the load order just after More Gifts from Children.esl). Custom patch LS2 Shadows of the Past.esl goes before LS2 Patches Merged.esp

**Extra Notes:**

To start the quest, go to any city and the courier will bring you a letter to start the first quest. Also, the main NPC won't always give you the second quest after completing the first one. If so, just save and reload and the NPC will then have the prompt available. From the mod page: quest 2 the Forgotten Prisoner sometimes refuses to start. It's a well known bug in questmods and easy to fix. After Herbert offered his merchant service save the game and reload.

**Comment by JaxomofRuatha** [comment]
Added this with most recent update!
