### ISSUE TITLE
FleshFX

### ISSUE THREAD

**Issue by chosti-factor** [JaxomofRuatha/ls2-extra-mods-unofficial#20]
**Name of the mod (please use whatever the Nexus title is):**

FleshFX

**Download link for the mod:**

https://www.nexusmods.com/skyrimspecialedition/mods/27456?tab=description

**Summary:**

From the mod page: Replaces the infamous alteration flesh glow with proper animated effects.

**LS2 Compatibility Status:**

Works well with 2.4.0

**Recommendation:**

* Current level of recommendation, high to low: Highly Recommended
* (Optional) add an actual review of the mod itself: Cool mage armor effects without glow.
 
**Official Patches:**

None

**Custom Patches:**

None needed

**Load/Install Order Notes:**

* Include the version of LS you are currently running as the base: 2.4.0
* Load anywhere. I currently have fleshfx.esp after Occlusion.

**Extra Notes:**

Tired of the mega-glowy flesh armor spells? Don't attract attention while sneaking! Use FleshFX. It will only place the effects on your skin, not your armor. Plus, the effects are very cool.

**Comment by JaxomofRuatha** [comment]
Added this with most recent update!
