### ISSUE TITLE
Beyond Reach

### ISSUE THREAD

**Issue by chosti-factor** [JaxomofRuatha/ls2-extra-mods-unofficial#21]
**Name of the mod (please use whatever the Nexus title is):**

Beyond Reach

**Download link for the mod:**

https://www.nexusmods.com/skyrimspecialedition/mods/3008

**Summary:**

From the mod page: Beyond Reach is a DLC sized mod that takes place in the east of High Rock, commonly known as The Reach. You will experience a story of intrigue, conspiracies sowed by both men and gods, and the struggles of those in the most squalid situations.

**LS2 Compatibility Status:**

Stable under 2.4.0 with custom patch

**Recommendation:**

* Current level of recommendation, high to low: Okay
* (Optional) add an actual review of the mod itself: Very large DLC with it's own world space. Voice acting is of variable quality. Quests are not fetch quests, which is cool. Architecture is substantially different from Skyrim.

**Official Patches:**

None

**Custom Patches:**

[LS2 - Beyonds Reach - Patch.zip](https://github.com/JaxomofRuatha/ls2-extra-mods-unofficial/files/5362723/LS2.-.Beyonds.Reach.-.Patch.zip)

Note to Jax: This mod touches a bit of everything. This patch is ok for LS2 base list, but more mods from the unofficial list are added, it probably will need additional patching. Music was not patched, as I didn't want to fuck things up too badly.

**Load/Install Order Notes:**

* Include the version of LS you are currently running as the base: 2.4.0
* Load order: arnima.esm goes right after More Gifts for Children.esl. LS2 - Beyond Reach - Patch.esp goes after bashed patch. I have it after occlusion.

**Extra Notes:**

Quest starts when you travel to a city. From the mod page: Head to any major city (PLAYER MUST BE LEVEL 5 OR ABOVE) in skyrim to find the Priestess and her bodyguard; Oliver. They will introduce you to the quest upon finishing their dialogue.

**Comment by JaxomofRuatha** [comment]
Uh...I hate to tell you this but I already have this mod included 😆 [Beyond Reach](https://github.com/JaxomofRuatha/ls2-extra-mods-unofficial/blob/master/mod-details/BeyondReach.md)

I can definitely add your feedback into the information for it though, not sure what the patch was but that doesn't seem to have attached. I think I was pretty thorough with patching though, so probably covered the same things? If you add it I can find out!

**Comment by chosti-factor** [comment]
LOL, smh at myself. I trust your patch is going to be much better than what I came up with, but I put it up anyhow in case You want to give me feedback.

**Comment by JaxomofRuatha** [comment]
Already added as mentioned, I can poke around the plugin at some point but it sounded like you might have done some comparing on your own, just let me know 😃
