### ISSUE TITLE
Personal Experience Addition - chosti-factor Strange Runes

### ISSUE THREAD

**Issue by chosti-factor** [JaxomofRuatha/ls2-extra-mods-unofficial#22]
**Mod Name:**

Strange Runes

**Recommendation:**

* Current level of recommendation, high to low: Highly Recommended

**Additional Official Patches:**

**Additional Custom Patches:**

**Custom Patches:**

**Load/Install Order Notes:**

**Extra Notes:**

Important: For Strange Runes version 3.5, you'll need to update the version of Papyrus Extender and FEC that are installed by default by LS2.

**Comment by JaxomofRuatha** [comment]
Updated in most recent version
