### ISSUE TITLE
Nordic Snow

### ISSUE THREAD

**Issue by chosti-factor** [JaxomofRuatha/ls2-extra-mods-unofficial#23]
**Name of the mod (please use whatever the Nexus title is):**

Nordic Snow (AKA HQ Snow Texture)

**Download link for the mod:**

https://www.nexusmods.com/skyrimspecialedition/mods/670/?tab=files

Get the non-BSA 3.4.3 version. This version is compatible with Majestic Mountains which is included in LS2.

**Summary:**

In my opinion, this snow looks more realistic than the vanilla Skyrim snow, I'm coming from a country with a lot of snow (Norway), so I guess you can say I know what I'm talking about. 

The vanilla texture has minor tiling issues and looks too dark and more like foam than snow - it just doesn't look realistic to me. They also had issues converting everything to the newest textures, which is why their snow with the footprint has a different shade. 

I was trying to go for a more crystallized look with my texture and at the same time overcome the shortcoming with vanilla. These textures have been worked on for a very long time and I now decided to port them over to Special Edition. 

**LS2 Compatibility Status:**

No compatibility issues.

**Recommendation:**

* Current level of recommendation, high to low: Highly Recommended
* (Optional) add an actual review of the mod itself: My personal snow mod favorite.

**Official Patches:**

None

**Custom Patches:**

[Nordic Snow Blended Roads Redone Patch.zip](https://github.com/JaxomofRuatha/ls2-extra-mods-unofficial/files/5397918/Nordic.Snow.Blended.Roads.Redone.Patch.zip)

This patch makes Nordic Snow work with Blended Roads.

**Load/Install Order Notes:**

* Include the version of LS you are currently running as the base: 2.5.0
* Nordic Snow is just after Hyperborean Snow in MO2's left pane. I disabled Hyperborean snow. Blended Roads Patch is after Nordic Snow wherever.

**Extra Notes:**

**Comment by JaxomofRuatha** [comment]
Added in most recent version
