### ISSUE TITLE
Sea of Spirits Shark Patch

### ISSUE THREAD

**Issue by chosti-factor** [JaxomofRuatha/ls2-extra-mods-unofficial#24]
Patch that makes the sharks behave in a less derpy manner. It tweaks their stats to make their movement slower, harder to jump on land, and less likely to engage in battles that end up with flying sharks.
[LS2 Sea of Spirits Patch.zip](https://github.com/JaxomofRuatha/ls2-extra-mods-unofficial/files/5406601/LS2.Sea.of.Spirits.Patch.zip)

**Comment by JaxomofRuatha** [comment]
Added in latest update!
