### ISSUE TITLE
Mod Addition - <A Cat's Life>

### ISSUE THREAD

**Issue by Day7-J** [JaxomofRuatha/ls2-extra-mods-unofficial#3]
**Name of the mod (please use whatever the Nexus title is):** A Cat's Life

**Download link for the mod:** https://www.nexusmods.com/skyrimspecialedition/mods/37250

**Summary:**

A Cat's Life aims to bring cats to the land of Skyrim in the most immersive and fun way possible. Towns and villages will have both stray and household cats wandering around who you can interact with. You'll be able to adopt cats through gaining their trust and affection and even purchase your own cats from pet stores.

**LS2 Compatibility Status:**

It worked pretty much "straight out of the box"

**Recommendation:**

Highly recommended because, I mean, it's cats man

**Official Patches:** N/A

**Custom Patches:** N/A

**Load/Install Order Notes:**

LS2 2.2.1
I tend to just smash stuff together, but I haven't had any issues with it just going at the end of my load order

**Extra Notes:** N/A

**Comment by JaxomofRuatha** [comment]
Added to mods!
