### ISSUE TITLE
Mod Addition - Swift Potion Reborn

### ISSUE THREAD

**Issue by WinterdrakeX** [JaxomofRuatha/ls2-extra-mods-unofficial#4]
**Swift Potion Reborn**

**Link:** https://www.nexusmods.com/skyrimspecialedition/mods/12293

**Summary:** An auto potion system with effect hotkeys!

Swift Potion Reborn is an auto potion system. When your Health/Magicka/Stamina reaches a level that you define as too low, a potion/food item will be used. A delay system will prevent potions from being used rapidly in succession. Effect hotkeys allow you to bind an effect to a single key and use any potion that has that effect.

**LS2 Compatibility Status:** Excellent (no issues, no patching required)

**Recommendation:** Highly Recommended

**Official Patches:**

N/A

**Custom Patches:**

N/A

**Load/Install Order Notes:**

(LS2 version 2.2.1)
Can be installed anywhere as this is very lightweight. Currently after Occlusion.esp.

**Extra Notes:**

This mod will save your life if nothing else will.

**Comment by JaxomofRuatha** [comment]
Added as new mod!
