### ISSUE TITLE
Mod Addition - Identity Crisis

### ISSUE THREAD

**Issue by WinterdrakeX** [JaxomofRuatha/ls2-extra-mods-unofficial#5]
**Identity Crisis**

**https://www.nexusmods.com/skyrimspecialedition/mods/39634?tab=files**

**Summary:**

Investigate the madness afflicting the Northern Asylum of Julianos, and earn the boon of the Madgod himself.
All glory to the Prince of Fools!
New enemies, spells, armour, weapons, and a player home await...

**LS2 Compatibility Status:** Excellent

**Recommendation:** Highly Recommended

* (Optional) add an actual review of the mod itself

**Official Patches:**

Wintersun Patch

https://www.nexusmods.com/skyrimspecialedition/mods/39634?tab=files

**Custom Patches:**

N/A

**Load/Install Order Notes:**

(LS2 version 2.2.1)

Identity Crisis.esp must be loaded before ELE_SSE.esp

Wintersun Patch loaded anywhere after Identity Crisis.esp and Wintersun - Faiths of Skyrim.esp. Currently after Occlusion.esp.

**Extra Notes:**

N/A

**Comment by JaxomofRuatha** [comment]
Added as new mod!
