### ISSUE TITLE
Mod Addition - Animated Wings Ultimate

### ISSUE THREAD

**Issue by WinterdrakeX** [JaxomofRuatha/ls2-extra-mods-unofficial#6]
**Animated Wings Ultimate**

**https://www.nexusmods.com/skyrimspecialedition/mods/34571?tab=files**

*Note: Download the Animated Wings Ultimate (No Flying Mod Integration)

**Summary:** 83 fully animated feathered, dragon, bound, and fairy wings packed with configurable immersive effects and customizable controls.

**LS2 Compatibility Status:**  Excellent ( no issues, no patching required).

**Recommendation:** Okay (Not really needed, but great otherwise.)

**Official Patches:**

N/A

**Custom Patches:**

N/A

**Load/Install Order Notes:**

(LS2 version 2.2.1)

Put Animated Wings Ultimate.esp before LS2 Patches Merged.esp

**Extra Notes:**

I recommended Animated Wings Ultimate (No Flying Mod Integration) because Flying Mod is said to be unstable.
You could still try the flying Mod version, just follow the instructions on the mod page of Flying Wings Ultimate.

**Comment by JaxomofRuatha** [comment]
Added as new mod!
