### ISSUE TITLE
Mod Addition - Aetherium Armor and Weapons

### ISSUE THREAD

**Issue by WinterdrakeX** [JaxomofRuatha/ls2-extra-mods-unofficial#7]
**Aetherium Armor and Weapons Compilation by lautasantenni**

**https://www.nexusmods.com/skyrimspecialedition/mods/2687?tab=files**

**Summary:**

Adds 2 Power Armor Sets and many weapons after unlocking the Aetherium Forge. Can be displayed at the museum using
the LOTD patch.

**LS2 Compatibility Status:** Good (no stability issues with or without the LOTD patch).

**Recommendation:** Highly Recommended

**Official Patches:**

LOTD Display Patch
https://www.nexusmods.com/skyrimspecialedition/mods/30980 (Note: contains 2 esps)

**Custom Patches:**

N/A

**Load/Install Order Notes:**

(LS2 version 2.2.1)
AetheriumSwordsnArmor.esp must be loaded before ELE_SSE.esp

DBM_AetheriumWeapons_Patch.esp and DBM_ISC_Patch loaded before Bashed Patch, 0.esp (NOTE: I reinstalled the Legacy of the Dragonborn Official Patches with a different name and no other patches enabled to get this)

**Extra Notes:**

Weapons and armor pieces are not currently marked by the Curator's Companion. Will still be displayed if auto-sorted.
Highly preferred to be installed if Aetherium Forge quest was still not started, since you could only find aetherium ingots on certain Dwemer ruins.

**Comment by JaxomofRuatha** [comment]
Added as new mod!
