### ISSUE TITLE
Helgen Reborn - NordWarUA Armor Replacer

### ISSUE THREAD

**Issue by WinterdrakeX** [JaxomofRuatha/ls2-extra-mods-unofficial#8]
**Helgen Reborn - NordWarUA Armor Replacer**

**https://www.nexusmods.com/skyrimspecialedition/mods/39292?tab=files**

**Summary:**

Replaces the guard armor in Helgen Reborn with a set matching the style of NordWarUA's guard armors. ESL flagged!

**LS2 Compatibility Status:**

Excellent (no issues, no patching required)

**Recommendation:**
Highly Recommended

**Official Patches:**

None

**Custom Patches:**

None

**Load/Install Order Notes:**

WinterdrakeX (LS2 version 2.2.1)
* Install anywhere after occlusion.esp

**Extra Notes:**

ESL Flagged!

**Comment by JaxomofRuatha** [comment]
Added as a new mod!
