### ISSUE TITLE
Jiub's Opus

### ISSUE THREAD

**Issue by WinterdrakeX** [JaxomofRuatha/ls2-extra-mods-unofficial#9]
**Jiub's Opus**

**https://www.nexusmods.com/skyrimspecialedition/mods/17056?tab=files**

**Summary:**

*Simple mod that adds quest markers for the Side quest Impatience of a Saint.

**LS2 Compatibility Status:**

*Excellent (no issues, no patching required)

**Recommendation:**

WinterdrakeX (Highly Recommend)

**Official Patches:**

*None

**Custom Patches:**

*None

**Load/Install Order Notes:**

* Anywhere after Occlusion.esp

**Extra Notes:**

Don't go wandering off in the Soul Cairn for eternity just for a small quest. ESL flagged!!

**Comment by JaxomofRuatha** [comment]
Added as a new mod!
